export const slides = [
  {
    id: '00-intro',
    title: 'Hi, I\u2019m Taylor',
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'intro' },
    subtitle: 'UX Design Lead at Launchpad',
    caption: 'I wanted to share a little about RGB colors and how they map to HSB.',
  },
  {
    id: '00b-acronyms',
    title: '',
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'acronyms' },
    caption: 'RGB stands for Red, Green, and Blue. HSB stands for Hue, Saturation, and Brightness.\nThese are two different ways to describe colors on computer screens.',
  },
  {
    id: '01-1bit',
    title: 'Black & White',
    titleMeta: { bits: 1, colorCount: 2, year: 1984, os: 'System 1.0' },
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'bw' },
    caption: 'But first, a little history. My first computer was a Macintosh Plus, which had exactly two colors, Black and White.',
  },
  {
    id: '02-sixteen',
    title: '16 Colors',
    titleMeta: { bits: 4, colorCount: 16, year: 1987, os: 'System 5' },
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'c16' },
    caption: 'Then came sixteen colors. Still a pretty small world... but suddenly things felt a little more alive.',
  },
  {
    id: '03-256',
    title: '256 Colors',
    titleMeta: { bits: 8, colorCount: 256, year: 1987, os: 'System 5' },
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'c256' },
    caption: '256 colors. Each one had a number, a fixed spot in a lookup table. You didn\'t describe the color, you referenced it.',
  },
  {
    id: '04-thousands',
    title: 'Thousands',
    titleMeta: { bits: 16, colorCount: 32768, year: 1990, os: 'System 6' },
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'thousands' },
    caption: 'Then thousands. Three channels - Red, Green, Blue - each a gradient from black to full intensity. That\'s where RGB came in.',
  },
  {
    id: '05-millions',
    title: 'Millions',
    titleMeta: { bits: 24, colorCount: 16777216, year: 1991, os: 'System 7' },
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'millions' },
    caption: 'Millions. 24 bits - 8 per channel. The Monitors panel still showed four bars, but the machine could now display any of 16.7 million colors.',
  },
  {
    id: '06-spectrum',
    title: 'The Full Spectrum',
    type: 'static',
    component: 'MonitorPanel',
    props: { mode: 'hsl-gradient' },
    caption: 'In reality, those millions of colors fill a continuous spectrum. Hue across, lightness top to bottom. Every color the screen can show.',
  },
  {
    id: '07-red',
    title: 'The Red Channel',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'large-preview'],
      lockedChannels: ['g', 'b'],
      initialHsb: { h: 0, s: 100, b: 100 },
      showRgbAnimate: true,

    },
    caption: 'Red is just a channel. Zero is black. 255 is full red. On its own, it\'s just a range.',
  },
  {
    id: '08-mixing',
    title: 'Mixing in Green and Blue',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'large-preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
      showRgbAnimate: true,

    },
    caption: 'Same idea for green and blue. Three separate channels. Each one from black to its full value.\nPut them together and you get a color. It works. But it\'s not always obvious where you\'ll land.',
  },
  {
    id: '09-hex',
    title: 'Describing Colors with Numbers',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'large-preview'],
      showHexInPreview: true,
      initialHsb: { h: 200, s: 80, b: 90 },
      showRgbAnimate: true,
    },
    caption: 'Hexadecimal values are used to describe colors as 6 character values. Each color channel has a value between 0-255, which can also be described as a float from 0 to 1.',
  },
  {
    id: '09-hsb',
    title: 'Finding HSB',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'hsb-sliders', 'large-preview'],
      showHexInPreview: true,
      showHsbInPreview: true,
      initialHsb: { h: 200, s: 80, b: 90 },
      showRgbAnimate: true,
    },
    caption: 'Then I found HSB. Hue, Saturation, Brightness. Suddenly I could think in terms of: what color is it? How rich is it? How bright is it?',
  },
  {
    id: '10-gap',
    title: 'The Gap',
    type: 'narrative',
    component: 'NarrativeSlide',
    props: {
      heading: 'RGB \u2194 HSB',
      subheading: 'How does one become the other?',
    },
    caption: 'I could use HSB. I could use RGB. But I didn\'t really understand how one became the other. What was the math?',
  },
  {
    id: '11-equations',
    title: 'The Equations',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'hsb-sliders', 'equations', 'large-preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'The hue, saturation, and brightness values are all derived from the RGB values. There\'s a real transformation happening.',
  },
  {
    id: '12-hexagon',
    title: 'The Color Hexagon',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['hexagon', 'rgb-sliders', 'hsb-sliders', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'And this is where it all clicks. The hexagon shows you where your color lives, and what\'s around it.',
  },
  {
    id: '13-complementary',
    title: 'Complementary Color',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['hexagon', 'conversions', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'The complementary color is exactly opposite on the wheel. 180 degrees away.',
  },
  {
    id: '14-operations',
    title: 'Color Operations',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['hexagon', 'conversions', 'rgb-sliders', 'hsb-sliders', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'From any color you pick, you can explore these relationships. Each one tells you something different about that color.',
  },
  {
    id: '15-journey',
    title: 'The Journey',
    type: 'narrative',
    component: 'NarrativeSlide',
    props: {
      heading: 'The Journey',
      subheading: '1-bit \u2192 16 \u2192 256 \u2192 RGB \u2192 Hex \u2192 HSB',
      body: 'It\'s all the same color. Just different ways of describing it.',
    },
    caption: 'That\'s the journey. From one bit to this. Every step was just finding a better language for something that was always there.',
  },
];
