export const slides = [
  {
    id: '01-1bit',
    title: '1-Bit Color: On or Off',
    type: 'static',
    component: 'PixelGrid',
    props: { bitDepth: 1 },
    caption: 'When I first used a computer, it was a Macintosh. And it had exactly two colors. Black and white. On or off. One bit.',
  },
  {
    id: '02-sixteen',
    title: 'Sixteen Colors',
    type: 'static',
    component: 'ColorPalette',
    props: { palette: 'cga16' },
    caption: 'Then came sixteen colors. Still a pretty small world... but suddenly things felt a little more alive.',
  },
  {
    id: '03-256',
    title: '256 Colors. A LUT.',
    type: 'static',
    component: 'ColorPalette',
    props: { palette: 'websafe256' },
    caption: '256 colors. Each one had a number, a fixed spot in a lookup table. You didn\'t describe the color, you referenced it.',
  },
  {
    id: '04-beyond',
    title: 'Beyond the List',
    type: 'narrative',
    component: 'NarrativeSlide',
    props: {
      heading: '256 \u2192 RGB',
      subheading: 'More colors than we could index.',
    },
    caption: 'After 256, the list didn\'t work anymore. There were too many colors. So we moved to describing colors directly. That\'s where RGB came in.',
  },
  {
    id: '05-red',
    title: 'The Red Channel',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders'],
      lockedChannels: ['g', 'b'],
      initialHsb: { h: 0, s: 100, b: 100 },
    },
    caption: 'Red is just a channel. Zero is black. 255 is full red. On its own, it\'s just a range.',
  },
  {
    id: '06-green-blue',
    title: 'Green and Blue',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders'],
      initialHsb: { h: 0, s: 100, b: 100 },
    },
    caption: 'Same idea for green and blue. Three separate channels. Each one from black to its full value.',
  },
  {
    id: '07-mixing',
    title: 'Mixing RGB',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'Put them together and you get a color. It works. But it\'s not always obvious where you\'ll land.',
  },
  {
    id: '08-hex',
    title: 'The Web Adds Hex',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'hex-input', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'Then the web came along and added hex values. Still RGB underneath, just written differently.',
  },
  {
    id: '09-hsb',
    title: 'Finding HSB',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'hsb-sliders', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'Then I found HSB. Hue, Saturation, Brightness. Suddenly I could think in terms of: what color is it? How rich is it? How bright is it?',
  },
  {
    id: '10-gap',
    title: 'The Gap',
    type: 'narrative',
    component: 'NarrativeSlide',
    props: {
      heading: 'RGB \u2194 HSB',
      subheading: 'How does one become the other?',
    },
    caption: 'I could use HSB. I could use RGB. But I didn\'t really understand how one became the other. What was the math?',
  },
  {
    id: '11-equations',
    title: 'The Equations',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['rgb-sliders', 'hsb-sliders', 'equations', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'The hue, saturation, and brightness values are all derived from the RGB values. There\'s a real transformation happening.',
  },
  {
    id: '12-hexagon',
    title: 'The Color Hexagon',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['hexagon', 'rgb-sliders', 'hsb-sliders', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'And this is where it all clicks. The hexagon shows you where your color lives, and what\'s around it.',
  },
  {
    id: '13-complementary',
    title: 'Complementary Color',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['hexagon', 'conversions', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'The complementary color is exactly opposite on the wheel. 180 degrees away.',
  },
  {
    id: '14-operations',
    title: 'Color Operations',
    type: 'interactive',
    component: 'PresentationColorPicker',
    props: {
      visiblePanels: ['hexagon', 'conversions', 'rgb-sliders', 'hsb-sliders', 'preview'],
      initialHsb: { h: 200, s: 80, b: 90 },
    },
    caption: 'From any color you pick, you can explore these relationships. Each one tells you something different about that color.',
  },
  {
    id: '15-journey',
    title: 'The Journey',
    type: 'narrative',
    component: 'NarrativeSlide',
    props: {
      heading: 'The Journey',
      subheading: '1-bit \u2192 16 \u2192 256 \u2192 RGB \u2192 Hex \u2192 HSB',
      body: 'It\'s all the same color. Just different ways of describing it.',
    },
    caption: 'That\'s the journey. From one bit to this. Every step was just finding a better language for something that was always there.',
  },
];
